---
title: ""
---

# Publications

### 2024

**T Panaïotis**, A Poteau, É Diamond Riquier, C Catalano, L Courchet, S Motreuil, L Coppola, M Picheral and JO Irisson. Temporal evolution of plankton and particles distribution across a mesoscale front during the spring bloom. *Limnology and Oceanography*. [10.1002/lno.12566](https://doi.org/10.1002/lno.12566)

M Laget, L Drago, **T Panaïotis**, R Kiko, L Stemmann, A Rogge, N Llopis-Monferrer, A Leynaert, JO Irisson and T Biard. Global census of the significance of giant mesopelagic protists to the marine carbon and silicon cycles. *Nature Communications* **15**: 3341. [10.1038/s41467-024-47651-4](http://dx.doi.org/10.1038/s41467-024-47651-4)

M Dugenne, M Corrales-Ugalde, JY Luo, R Kiko, TD O'Brien, JO Irisson, F Lombard, L Stemmann, C Stock, CR Anderson, M Babin, N Bhairy, S Bonnet, F Carlotti, A Cornils, ET Crockford, P Daniel, C Desnos, L Drago, A Elineau, A Fischer, N Grandrémy, PL Grondin, L Guidi, C Guieu, H Hauss, K Hayashi, JA Huggett, L Jalabert, L Karp-Boss, KM Kenitz, RM Kudela, M Lescot, C Marec, A McDonnell, Z Mériguet, B Niehoff, M Noyon, **T Panaïotis**, E Peacock, M Picheral, E Riquier, C Roesler, JB Romagnan, HM Sosik, G Spencer, J Taucher, C Tilliette and M Vilain. First release of the Pelagic Size Structure database: global datasets of marine size spectra obtained from plankton imaging devices, Earth System Science Data, 16, 2971–2999, [10.5194/essd-16-2971-2024](https://doi.org/10.5194/essd-16-2971-2024)

**T Panaïotis**, E Amblard, G Boniface-Chang, G Dulac-Arnold, T Biard, B Blanc, L Caray--Counil, C Desnos, A Elineau, L Jalabert, R Kiko, F Lombard, M Picheral, JB Romagnan, L Stemmann and JO Irisson. Classification benchmark for several large plankton images datasets: Convolutional Neural Networks improve detection of rare taxa. Submitted to *Limnology and Oceanography: Methods*.

**T Panaïotis**, J Wilson and BB Cael. A machine learning-based dissolved organic carbon climatology. Submitted to *Limnology and Oceanography: Letters*.

**T Panaïotis**, T Biard, L Caray--Counil, R Faillettaz, J Luo, CM Guigand, RK Cowen and JO Irisson. High throughput in situ imaging reveals complex ecological behaviour of giant mixotrophic protists. Written as thesis chapter #6, to be submitted to *PNAS*.

### 2023

**T Panaïotis**, M Babin, T Biard, F Carlotti, L Coppola, L Guidi, H Hauss, L Karp-Boss, R Kiko, F Lombard, AMP McDonnell, M Picheral, A Rogge, AM Waite, L Stemmann and JO Irisson (2023). Three major mesoplanktonic communities resolved by in situ imaging in the upper 500 m of the global ocean. *Global Ecology and Biogeography*. [10.1111/geb.13741](https://doi.org/10.1111/geb.13741)

### 2022

**T Panaïotis**, L Caray--Counil, B Woodward, MS Schmid, D Daprano, ST Tsai, CM Sullivan, RK Cowen and J-O Irisson (2022). Content-Aware Segmentation of Objects Spanning a Large Size Range: Application to Plankton Images. *Frontiers in Marine Science* 9. [10.3389/fmars.2022.870005](https://doi.org/10.3389/fmars.2022.870005)

L Drago, **T Panaïotis**, JO Irisson, M Babin, T Biard, F Carlotti, L Coppola, L Guidi, H Hauss, L Karp-Boss, F Lombard, AMP McDonnell, M Picheral, A Rogge, AM Waite, L Stemmann and R Kiko (2022). Global Distribution of Zooplankton Biomass Estimated by In Situ Imaging and Machine Learning. *Frontiers in Marine Science*, 9. [10.3389/fmars.2022.894372](https://doi.org/10.3389/fmars.2022.894372)

AT Greer, MS Schmid, PI Duffy, KL Robinson, MA Genung, JY Luo, **T Panaïotis**, C Briseño-Avena, ME Frischer, S Sponaugle and RK Cowen (2022). In situ imaging across ecosystems to resolve the fine-scale oceanographic drivers of a globally significant planktonic grazer. *Limnology and Oceanography*, 68, 192-207. [10.1002/lno.12259](https://doi.org/10.1002/lno.12259)

### 2018

A Guez, **T Panaïotis**, H Peyre and F Ramus (2018). Predictors of the IQ-achievement gap in France: A longitudinal analysis. *Intelligence*, 69: 104-116. [10.1016/j.intell.2018.05.008](https://doi.org/10.1016/j.intell.2018.05.008)

------------------------------------------------------------------------

# Conference talks

### 2023

**T Panaïotis**, T Biard, L Caray--Counil, R Faillettaz, J Luo, CM Guigand, RK Cowen and JO Irisson (2023). High throughput in situ imaging reveals complex ecological behaviour of giant mixotrophic protists. *ASLO Aquatic Science Meeting* (Palma de Majorque, Spain). [Slides](reports/2023_aslo_rhizaria.pdf)

**T Panaïotis**, A Poteau, É Diamond Riquier, C Catalano, L Courchet, S Motreuil, L Coppola, M Picheral and JO Irisson (2023). Temporal evolution of plankton and particles distribution across a mesoscale front during the spring bloom. *ASLO Aquatic Science Meeting* (Palma de Majorque, Spain). Presented by JO Irisson. [Slides](reports/2023_aslo_glider.pdf)

### 2022

**T Panaïotis**, L Caray--Counil, B Woodward, S Schmid, D Daprano, ST Tsai, CM Sullivan, RK Cowen and JO Irisson (2022). Content-Aware Segmentation of Objects Spanning a Large Size Range: Application to Plankton Images. *ICES Annual Science Conference* (Dublin, Ireland). [Slides](reports/2022_ices_segmentation.pdf)

**T Panaïotis**, L Caray-Counil, R Faillettaz, JY Luo, CM Guigand, RK Cowen and JO Irisson (2022). Meter-Scale Plankton Distribution across a Mesoscale Front. *Ocean Sciences Meeting* (Virtual Meeting). [Slides](reports/2022_osm_distribution.pdf)

### 2021

**T Panaïotis**, G Boniface-Chang, G Dulac-Arnold, B Woodward and JO Irisson (2021). Benchmark of Image Classification Using Several Large Plankton Datasets: Convolutional Neural Networks Improve Detection of Rare Taxa. *Aquatic Sciences Meeting* (Virtual Meeting). [Slides](reports/2021_aslo_classif.pdf)

### 2020

**T Panaïotis**, M Babin, T Biard, F Carlotti, L Coppola, L Guidi, H Hauss, L Karp-Boss, R Kiko, F Lombard, A MP McDonnell, M Picheral, A Rogge, A M Waite, L Stemmann and JO Irisson (2020). Typology of Plankton Communities Seen by In Situ Imaging, from the Epi to the Mesopelagic Layers of the Global Ocean. *Ocean Sciences Meeting* (San Diego, USA). [Slides](reports/2020_osm_typology.pdf)

------------------------------------------------------------------------

# Seminars & Workshops

### 2024

**T Panaïotis** and BB Cael (2024). Machine Learning for feature detection: linking zooplankton diversity and particulate organic carbon. *CALIPSO annual meeting* (Norwich, UK). [Slides](reports/2024_calipso_ml.pdf)

**T Panaïotis**, J Wilson and BB Cael. A Machine Learning based Climatology of Dissolved Organic Carbon. *Machine Learning for Earth Observation Workshop* (Exeter, UK). [Poster](reports/Poster_DOC.pdf)

### 2022

**T Panaïotis**, L Caray--Counil, B Woodward, MS Schmid, D Daprano, ST Tsai, CM Sullivan, RK Cowen, and JO Irisson (2022). Content-Aware Segmentation of Objects Spanning a Large Size Range: Application to Plankton Images. *ImaginEcology2* (Lyon, France).

**T Panaïotis**, A Poteau, E Riquier, M Picheral, C Catalano, L Coppola and JO Irisson (2022). Fine-scale plankton distribution across the Ligurian Front from glider and UVP6. *UVP users meeting* (Villefranche-sur-Mer, France). [Slides](reports/2022_uvp_meeting.pdf)

**T Panaïotis**, B Woodward, L Caray-Counil and JO Irisson (2022). Extraction d'informations écologiques à partir de gros volumes de données d'imagerie quantitative. *Journée Bio-informatique, BioGenOuest* (Virtual Meeting). Présenté par JO Irisson.

**T Panaïotis**, L Caray-Counil, R Faillettaz, JY Luo, CM Guigand, RK Cowen and JO Irisson (2022). Meter-Scale Plankton Distribution across a Mesoscale Front. *FORMAL Winter Webinars* (Virtual Meeting).

### 2021

**T Panaïotis** (2021). CNN for classification and segmentation of grayscale plankton images. *ISCD-FORMAL Marine Big Data* (Virtual Meeting).

### 2020

**T Panaïotis** and L Vilgrain (2020). Plankton Imaging Data. *ISCD-FORMAL Marine Big Data* (Virtual Meeting).

------------------------------------------------------------------------

# Reports

**PhD Thesis** \| Plankton distribution across scales: contribution from artificial intelligence to plankton ecology \| Supervised by Dr Jean-Olivier Irisson \| Laboratoire d'Océanographie de Villefranche. [Manuscript](reports/panaiotis_thesis_revised.pdf){target="_blank"}

**Master's intership** \| Typology of plankton communities seen by *in situ* imaging \| Supervised by Dr Jean-Olivier Irisson and Pr Lars Stemmann \| Laboratoire d'Océanographie de Villefranche. [Report (French)](reports/Rapport_M2_Thelma_Panaiotis.pdf){target="_blank"}

**Master's intership** \| Dynamics of fish schooling behaviour in relation to predator abundance \| Supervised by Prof Jessica Meeuwig, Dr Phil Bouchet and Dr Shanta Barley \| Centre for Marine Futures, University of Western Australia, Perth, Australia. [Report](reports/PANAIOTIS_ARPE_Thesis_final.pdf){target="_blank"}

**Master's intership** \| Effect of priority education facilities on the IQ-achievement gap \| Supervised by Franck Ramus and Hugo Peyre \| Laboratoire de Sciences Cognitives et Psycholinguistique, École Normale Supérieure. [Report (French)](reports/Rapport%20stage%20M1.pdf){target="_blank"}
